hardware_interface:
  sim_control_mode: 0
  joints:
    - arm_flex_joint
    - arm_lift_joint
    - arm_roll_joint
    - base_l_drive_wheel_joint
    - base_l_passive_wheel_x_frame_joint
    - base_l_passive_wheel_y_frame_joint
    - base_l_passive_wheel_z_joint
    - base_r_drive_wheel_joint
    - base_roll_joint
    - base_r_passive_wheel_x_frame_joint
    - base_r_passive_wheel_y_frame_joint
    - base_r_passive_wheel_z_joint
    - hand_l_spring_proximal_joint
    - hand_motor_joint
    - hand_r_spring_proximal_joint
    - head_pan_joint
    - head_tilt_joint
    - wrist_flex_joint
    - wrist_roll_joint
    - odom_x
    - odom_y
    - odom_t
generic_hw_control_loop:
  loop_hz: &loop_rate 100
  cycle_time_error_threshold: 0.015
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_rate
whole_body_controller:
  type: position_controllers/JointTrajectoryController  
  joints:
    - arm_flex_joint
    - arm_lift_joint
    - arm_roll_joint
    - head_pan_joint
    - head_tilt_joint
    - wrist_flex_joint
    - wrist_roll_joint
    - odom_x
    - odom_y
    - odom_t
    - hand_r_spring_proximal_joint
    - hand_l_spring_proximal_joint